### ISSUE TITLE
Wrap evil-spammer with HTTP server

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/evil-tools#10]
Having this wrapper outside allows us to spawn the spammer via HTTP requests.
A new spammer instance is launched for each start command, similar to the interactive mode.

For example:
```
localhost:8080/spammer?cmd=start&scenario=ds&duration=30s
localhost:8080/spammer?cmd=stop
```

```[tasklist]
### Tasks
- [ ] HTTP server (ref: inx-spammer)
- [ ] Wrap current options/flags into query parameters
- [ ] Make sure to have defaults set if flags are not provided
- [ ] Return `SpamDetails` as response
```

**Comment by muXxer** [comment]
We won't support that for now. Usage via CLI is totally fine for our usecase.
