### ISSUE TITLE
Account creation and transition

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/evil-tools#11]
```[tasklist]
### Tasks
- [x] Test implicit account transition
- [x] transition implicit to account
- [x] use faucet to get mana, add command
- [x] finish account creation with the faucet account
```
