### ISSUE TITLE
Make sure all scenarios work over several runs

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/evil-tools#6]
Make sure all scenarios are working with repeated runs of the evil spammer without restarting the network.
```[tasklist]
### Tasks
- [x] Revive deep spam
- [ ] Test evil scenarios over several runs
- [ ] Test all scenarios
```
